# Generated by Django 2.1.4 on 2019-02-15 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20190214_2137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='prince',
            new_name='price',
        ),
    ]
